### ISSUE TITLE
Merge normal and COVID templates

### ISSUE THREAD

**Issue by miabonardi** [SuffolkLITLab/docassemble-ConsumerDefaultMC#13]
- Add question if the user is trying to vacate because of COVID. 
- Explain to user why they can use COVID as a reason to vacate the judgment. Screen needs an explanation on it. 
- This was a change requested in the 8/16/20 demo.

**Comment by mikecronin7** [comment]
The templates have already been combined

**Comment by miabonardi** [comment]
Merged code and templates are on a new branch.
