### ISSUE TITLE
Good idea to delete branch after merging

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-ConsumerDefaultMC#25]
[sendtocourtcode](https://github.com/SuffolkLITLab/docassemble-ConsumerDefaultMC/tree/sendtocourtcode)

I think you can use the rubbish bin icon to the right of the purple word "merged" on the [overview of branches](https://github.com/SuffolkLITLab/docassemble-ConsumerDefaultMC/branches) page.
double check w @plocket

**Comment by miabonardi** [comment]
@plocket suggests we do not merge this branch with master right now because it is broken.

**Comment by miabonardi** [comment]
Fixed.

**Comment by miabonardi** [comment]
Fixed.
