### ISSUE TITLE
Paragraph precedent

### ISSUE THREAD

**Issue by mikecronin7** [SuffolkLITLab/docassemble-ConsumerDefaultMC#4]
The COVID paragraph will be specifically for the covid pandemic issues. The pparagraph about being unware of the court date will take over precedent on most excuses.

It should be possible to check both boxes as a person can use both excuses to try and push their motion

**Comment by miabonardi** [comment]
> It should be possible to check both boxes as a person can use both excuses to try and push their motion

@mikecronin7 So do we just need to change them from radio buttons to choices?

**Comment by mikecronin7** [comment]
Consensus was that it would be best if there was  a blended paragraph using both covid and not knowing about the court date as an excuse if the user wanted to select both. SME Matt Brooks said he would write one up for us.

**Comment by mikecronin7** [comment]
Sent Matt an Email about this

**Comment by mikecronin7** [comment]
changed the template
