### ISSUE TITLE
Plaintiff's name question

### ISSUE THREAD

**Issue by miabonardi** [SuffolkLITLab/docassemble-ConsumerDefaultMC#7]
For `Page id: other party info`, if there can be more than one plaintiff, should we add a list collect?

**Comment by mikecronin7** [comment]
Shouldn't have more than one plantiff or more than one defendant eitther.

**Comment by miabonardi** [comment]
Then should we change "PLAINTIFF(S) WHO ARE PARTIES TO THIS JUDGMENT" to "PLAINTIFF WHO IS PARTY TO THIS JUDGMENT"?

@CaroRob

**Comment by miabonardi** [comment]
Should be singular and lowercase. 

Make not required. 

Add explanatory text in the subquestion to explain that Plaintiff is the creditor or judgment creditor.

**Comment by mikecronin7** [comment]
Completed, added more explanation for the name, made it not required and changed the field to "Plaintiff Name:"
