### ISSUE TITLE
Add additional information to intro kickout screen

### ISSUE THREAD

**Issue by miabonardi** [SuffolkLITLab/docassemble-ConsumerDefaultMC#9]
- The kickout screen `id: kickout screen no paperwork` needs additional information and a link 
- This was a change requested in the 8/16/20 demo.

**Comment by mikecronin7** [comment]
I can add the Consumer Intake Line: 617-603-1671 which Matt Brooks gave me. 

I will look for a website to add

**Comment by miabonardi** [comment]
This issue has merged with Issue #21.
